export interface Colonia {
  id: number;
  nombre: string;
  tipo: string | null;
  codigo_postal: string | null;
  id_municipio: number;
}

export const COLONIAS_MOCK: Colonia[] = [
  { id: 1, nombre: "Zona Centro", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 2, nombre: "Campestre Residencial I", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 3, nombre: "1 de Mayo", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 4, nombre: "11 de Febrero", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 5, nombre: "15 de Enero", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 6, nombre: "17 de Junio", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 7, nombre: "2 de Junio", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 8, nombre: "2 de Octubre", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 9, nombre: "20 Aniversario", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 10, nombre: "22 de Septiembre", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 11, nombre: "24 de Febrero", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 12, nombre: "24 de Junio", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 13, nombre: "27 de Noviembre", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 14, nombre: "3 de Mayo", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 15, nombre: "Abelardo Rodríguez", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 16, nombre: "Abraham González", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 17, nombre: "Abraham González FOVISSSTE", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 18, nombre: "Acequias de Tabalaopa I y II", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 19, nombre: "Adelitas", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 20, nombre: "Adición Universidad", tipo: null, codigo_postal: null, id_municipio: 14 },
  { id: 21, nombre: "Residencial los Trigales", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 22, nombre: "Ciudad Cuauhtémoc Centro", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 23, nombre: "3 Lagunitas", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 24, nombre: "6 de Enero", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 25, nombre: "A Maldonado", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 26, nombre: "Alicantes", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 27, nombre: "Altavista", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 28, nombre: "Ampliación Barrio Lerdo", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 29, nombre: "Ampliación Francisco Villa", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 30, nombre: "Ampliación Lázaro Cárdenas", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 31, nombre: "Ampliación República", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 32, nombre: "Ampliación Valle de Anáhuac", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 33, nombre: "Américas", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 34, nombre: "Anáhuac Centro", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 35, nombre: "Arroyo del Agua", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 36, nombre: "Arturo Rodríguez", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 37, nombre: "Barraganes", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 38, nombre: "Barrio Delicias", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 39, nombre: "Barrio Lerdo", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 40, nombre: "Barrio Santa María", tipo: null, codigo_postal: null, id_municipio: 18 },
  { id: 41, nombre: "Ciudad Delicias Centro", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 42, nombre: "1ro de Mayo", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 43, nombre: "31 de Octubre", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 44, nombre: "Abarrotes la Granja", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 45, nombre: "Abraham González (La Quemada)", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 46, nombre: "Agua Azul", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 47, nombre: "Alameda", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 48, nombre: "Alberto García", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 49, nombre: "Albino Loya (San Antonio)", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 50, nombre: "Alta Vista", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 51, nombre: "Altavista", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 52, nombre: "Ampliación Linda Vista", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 53, nombre: "Armendáriz", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 54, nombre: "Bella Vista", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 55, nombre: "Benito Juárez", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 56, nombre: "Benjamín Martínez", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 57, nombre: "Betania", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 58, nombre: "Buena Vista (Los Pavos)", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 59, nombre: "Bugambilias", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 60, nombre: "Cadete Agustín Melgar", tipo: null, codigo_postal: null, id_municipio: 20 },
  { id: 61, nombre: "Bosques del Valle", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 62, nombre: "Centro", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 63, nombre: "1 de Mayo", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 64, nombre: "1 de Septiembre", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 65, nombre: "1 de Septiembre Ampliación", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 66, nombre: "12 de Julio", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 67, nombre: "15 de Enero", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 68, nombre: "15 de Mayo", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 69, nombre: "16 de Septiembre", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 70, nombre: "2da. Burócrata", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 71, nombre: "3 Jacales", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 72, nombre: "3ra. Burócrata", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 73, nombre: "5 de Mayo", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 74, nombre: "6 de Enero", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 75, nombre: "6 de Mayo", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 76, nombre: "9 de Septiembre (CDP)", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 77, nombre: "Acacias", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 78, nombre: "Acequias del Sur", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 79, nombre: "Adolfo López Mateos", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 80, nombre: "Adriana", tipo: null, codigo_postal: null, id_municipio: 37 },
  { id: 81, nombre: "Primer Cuadro (Centro)", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 82, nombre: "10 de Mayo", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 83, nombre: "12 de Octubre", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 84, nombre: "18 de Marzo", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 85, nombre: "20 de Noviembre Nuevo", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 86, nombre: "20 de Noviembre Viejo", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 87, nombre: "24 de Febrero", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 88, nombre: "28 de Junio", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 89, nombre: "5 de Mayo", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 90, nombre: "75 (Heriberto Valdez Romero)", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 91, nombre: "9 de Diciembre", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 92, nombre: "Adolfo Lopez Mateos", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 93, nombre: "Aduana", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 94, nombre: "Agua Nueva", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 95, nombre: "Ahome Centro", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 96, nombre: "Ahome Independencia", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 97, nombre: "Ahome Independiente", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 98, nombre: "Albergue Louisiana", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 99, nombre: "Alcázar del Country", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 100, nombre: "Alejandro Peña", tipo: null, codigo_postal: null, id_municipio: 68 },
  { id: 101, nombre: "Badiraguato", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 102, nombre: "Agua Amarilla", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 103, nombre: "Aguaje Grande", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 104, nombre: "Agujas", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 105, nombre: "Alcoyonqui", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 106, nombre: "Alisitos", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 107, nombre: "Alisos", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 108, nombre: "Alisos (Alisitos)", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 109, nombre: "Arroyo Seco", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 110, nombre: "Arroyo de los Payán", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 111, nombre: "Atorivito", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 112, nombre: "Babunica", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 113, nombre: "Bacacoragua", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 114, nombre: "Bamopa", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 115, nombre: "Batacomito", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 116, nombre: "Batequitas", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 117, nombre: "Batopito", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 118, nombre: "Baymusari", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 119, nombre: "Boca de Arroyo", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 120, nombre: "Caiquiva", tipo: null, codigo_postal: null, id_municipio: 70 },
  { id: 121, nombre: "Centro", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 122, nombre: "Campestre Tres Ríos", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 123, nombre: "10 de Abril", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 124, nombre: "10 de Mayo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 125, nombre: "12 de Diciembre", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 126, nombre: "16 de Septiembre", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 127, nombre: "18 de Marzo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 128, nombre: "20 de Noviembre", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 129, nombre: "21 de Marzo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 130, nombre: "22 de Diciembre", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 131, nombre: "26 de Abril", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 132, nombre: "3 Ríos", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 133, nombre: "4 de Marzo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 134, nombre: "5 de Febrero", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 135, nombre: "5 de Mayo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 136, nombre: "5° Álvarez", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 137, nombre: "6 de Enero", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 138, nombre: "7 Gotas", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 139, nombre: "8 de Febrero", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 140, nombre: "9 de Marzo", tipo: null, codigo_postal: null, id_municipio: 74 },
  { id: 141, nombre: "Centro", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 142, nombre: "15 de Octubre", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 143, nombre: "17 de Mayo", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 144, nombre: "18 de Marzo", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 145, nombre: "2 de Octubre", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 146, nombre: "22-15 [Campo Pesquero]", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 147, nombre: "24 de Febrero", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 148, nombre: "5 de Mayo (Agua Blanca)", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 149, nombre: "6 de Mayo", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 150, nombre: "Abelardo L. Rodríguez", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 151, nombre: "Adolfo Ruiz Cortinez", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 152, nombre: "Adolfo Ruiz Cortinez Dos", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 153, nombre: "Agua Blanca", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 154, nombre: "Agua Blancona", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 155, nombre: "Agua Escondida", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 156, nombre: "Alamito Caimanero", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 157, nombre: "Ampliación 24 de Febrero", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 158, nombre: "Ampliación Leyva Solano", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 159, nombre: "Ampliación Santa María", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 160, nombre: "Ayuntamiento 92", tipo: null, codigo_postal: null, id_municipio: 78 },
  { id: 161, nombre: "Sábalo Country Club", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 162, nombre: "Centro", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 163, nombre: "11 Ríos", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 164, nombre: "12 de Mayo", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 165, nombre: "20 de Noviembre", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 166, nombre: "23 de Noviembre", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 167, nombre: "2a Ampliación Felipe Angeles", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 168, nombre: "2da. Ampliación Valle de Urias", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 169, nombre: "5a. Gaviotas", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 170, nombre: "5ta Chapalita", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 171, nombre: "7 de Abril", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 172, nombre: "Agustina Ramírez", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 173, nombre: "Alameda", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 174, nombre: "Alfonso G. Calderón", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 175, nombre: "Alfredo V. Bonfil", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 176, nombre: "Almar", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 177, nombre: "Ampl. Lico Velarde", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 178, nombre: "Ampl. Lomas del Ébano", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 179, nombre: "Ampliación Esperanza", tipo: null, codigo_postal: null, id_municipio: 79 },
  { id: 180, nombre: "Ampliación Francisco Alarcón (Venadillo II)", tipo: null, codigo_postal: null, id_municipio: 79 },
];
