export interface Municipio {
  id: number;
  nombre: string;
  codigo_postal: string | null;
  estado_id: number;
}

export const MUNICIPIOS_MOCK: Municipio[] = [
  { id: 1, nombre: "Ahumada", codigo_postal: null, estado_id: 2 },
  { id: 2, nombre: "Aldama", codigo_postal: null, estado_id: 2 },
  { id: 3, nombre: "Allende", codigo_postal: null, estado_id: 2 },
  { id: 4, nombre: "Aquiles Serdán", codigo_postal: null, estado_id: 2 },
  { id: 5, nombre: "Ascensión", codigo_postal: null, estado_id: 2 },
  { id: 6, nombre: "Bachíniva", codigo_postal: null, estado_id: 2 },
  { id: 7, nombre: "Balleza", codigo_postal: null, estado_id: 2 },
  { id: 8, nombre: "Batopilas", codigo_postal: null, estado_id: 2 },
  { id: 9, nombre: "Bocoyna", codigo_postal: null, estado_id: 2 },
  { id: 10, nombre: "Buenaventura", codigo_postal: null, estado_id: 2 },
  { id: 11, nombre: "Camargo", codigo_postal: null, estado_id: 2 },
  { id: 12, nombre: "Carichí", codigo_postal: null, estado_id: 2 },
  { id: 13, nombre: "Casas Grandes", codigo_postal: null, estado_id: 2 },
  { id: 14, nombre: "Chihuahua", codigo_postal: null, estado_id: 2 },
  { id: 15, nombre: "Chínipas", codigo_postal: null, estado_id: 2 },
  { id: 16, nombre: "Coronado", codigo_postal: null, estado_id: 2 },
  { id: 17, nombre: "Coyame del Sotol", codigo_postal: null, estado_id: 2 },
  { id: 18, nombre: "Cuauhtémoc", codigo_postal: null, estado_id: 2 },
  { id: 19, nombre: "Cusihuiriachi", codigo_postal: null, estado_id: 2 },
  { id: 20, nombre: "Delicias", codigo_postal: null, estado_id: 2 },
  { id: 21, nombre: "Dr. Belisario Domínguez", codigo_postal: null, estado_id: 2 },
  { id: 22, nombre: "El Tule", codigo_postal: null, estado_id: 2 },
  { id: 23, nombre: "Galeana", codigo_postal: null, estado_id: 2 },
  { id: 24, nombre: "Gran Morelos", codigo_postal: null, estado_id: 2 },
  { id: 25, nombre: "Guachochi", codigo_postal: null, estado_id: 2 },
  { id: 26, nombre: "Guadalupe", codigo_postal: null, estado_id: 2 },
  { id: 27, nombre: "Guadalupe y Calvo", codigo_postal: null, estado_id: 2 },
  { id: 28, nombre: "Guazapares", codigo_postal: null, estado_id: 2 },
  { id: 29, nombre: "Guerrero", codigo_postal: null, estado_id: 2 },
  { id: 30, nombre: "Gómez Farías", codigo_postal: null, estado_id: 2 },
  { id: 31, nombre: "Hidalgo del Parral", codigo_postal: null, estado_id: 2 },
  { id: 32, nombre: "Huejotitán", codigo_postal: null, estado_id: 2 },
  { id: 33, nombre: "Ignacio Zaragoza", codigo_postal: null, estado_id: 2 },
  { id: 34, nombre: "Janos", codigo_postal: null, estado_id: 2 },
  { id: 35, nombre: "Jiménez", codigo_postal: null, estado_id: 2 },
  { id: 36, nombre: "Julimes", codigo_postal: null, estado_id: 2 },
  { id: 37, nombre: "Juárez", codigo_postal: null, estado_id: 2 },
  { id: 38, nombre: "La Cruz", codigo_postal: null, estado_id: 2 },
  { id: 39, nombre: "López", codigo_postal: null, estado_id: 2 },
  { id: 40, nombre: "Madera", codigo_postal: null, estado_id: 2 },
  { id: 41, nombre: "Maguarichi", codigo_postal: null, estado_id: 2 },
  { id: 42, nombre: "Manuel Benavides", codigo_postal: null, estado_id: 2 },
  { id: 43, nombre: "Matachí", codigo_postal: null, estado_id: 2 },
  { id: 44, nombre: "Matamoros", codigo_postal: null, estado_id: 2 },
  { id: 45, nombre: "Meoqui", codigo_postal: null, estado_id: 2 },
  { id: 46, nombre: "Morelos", codigo_postal: null, estado_id: 2 },
  { id: 47, nombre: "Moris", codigo_postal: null, estado_id: 2 },
  { id: 48, nombre: "Namiquipa", codigo_postal: null, estado_id: 2 },
  { id: 49, nombre: "Nonoava", codigo_postal: null, estado_id: 2 },
  { id: 50, nombre: "Nuevo Casas Grandes", codigo_postal: null, estado_id: 2 },
  { id: 51, nombre: "Ocampo", codigo_postal: null, estado_id: 2 },
  { id: 52, nombre: "Ojinaga", codigo_postal: null, estado_id: 2 },
  { id: 53, nombre: "Praxedis G. Guerrero", codigo_postal: null, estado_id: 2 },
  { id: 54, nombre: "Riva Palacio", codigo_postal: null, estado_id: 2 },
  { id: 55, nombre: "Rosales", codigo_postal: null, estado_id: 2 },
  { id: 56, nombre: "Rosario", codigo_postal: null, estado_id: 2 },
  { id: 57, nombre: "San Francisco de Borja", codigo_postal: null, estado_id: 2 },
  { id: 58, nombre: "San Francisco de Conchos", codigo_postal: null, estado_id: 2 },
  { id: 59, nombre: "San Francisco del Oro", codigo_postal: null, estado_id: 2 },
  { id: 60, nombre: "Santa Bárbara", codigo_postal: null, estado_id: 2 },
  { id: 61, nombre: "Santa Isabel", codigo_postal: null, estado_id: 2 },
  { id: 62, nombre: "Satevó", codigo_postal: null, estado_id: 2 },
  { id: 63, nombre: "Saucillo", codigo_postal: null, estado_id: 2 },
  { id: 64, nombre: "Temósachic", codigo_postal: null, estado_id: 2 },
  { id: 65, nombre: "Urique", codigo_postal: null, estado_id: 2 },
  { id: 66, nombre: "Uruachi", codigo_postal: null, estado_id: 2 },
  { id: 67, nombre: "Valle de Zaragoza", codigo_postal: null, estado_id: 2 },
  { id: 68, nombre: "Ahome", codigo_postal: null, estado_id: 1 },
  { id: 69, nombre: "Angostura", codigo_postal: null, estado_id: 1 },
  { id: 70, nombre: "Badiraguato", codigo_postal: null, estado_id: 1 },
  { id: 71, nombre: "Choix", codigo_postal: null, estado_id: 1 },
  { id: 72, nombre: "Concordia", codigo_postal: null, estado_id: 1 },
  { id: 73, nombre: "Cosalá", codigo_postal: null, estado_id: 1 },
  { id: 74, nombre: "Culiacán", codigo_postal: null, estado_id: 1 },
  { id: 75, nombre: "El Fuerte", codigo_postal: null, estado_id: 1 },
  { id: 76, nombre: "Elota", codigo_postal: null, estado_id: 1 },
  { id: 77, nombre: "Escuinapa", codigo_postal: null, estado_id: 1 },
  { id: 78, nombre: "Guasave", codigo_postal: null, estado_id: 1 },
  { id: 79, nombre: "Mazatlán", codigo_postal: null, estado_id: 1 },
  { id: 80, nombre: "Mocorito", codigo_postal: null, estado_id: 1 },
  { id: 81, nombre: "Navolato", codigo_postal: null, estado_id: 1 },
  { id: 82, nombre: "Rosario", codigo_postal: null, estado_id: 1 },
  { id: 83, nombre: "Salvador Alvarado", codigo_postal: null, estado_id: 1 },
  { id: 84, nombre: "San Ignacio", codigo_postal: null, estado_id: 1 },
  { id: 85, nombre: "Sinaloa", codigo_postal: null, estado_id: 1 },
];
